version: "2"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>
      - MSSQL_PID=Express
    volumes:
      - ./backups/nytest_2023.bak:/backup.bak:ro
